//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class day
    {
        public day()
        {
            this.time_by_day = new HashSet<time_by_day>();
        }
    
        public int day1 { get; set; }
        public string week_day { get; set; }
    
        public virtual ICollection<time_by_day> time_by_day { get; set; }
    }
}
