//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dong_ho_sales
    {
        public string ten_dh { get; set; }
        public int so_luong { get; set; }
        public decimal so_tien { get; set; }
        public string masp { get; set; }
    
        public virtual dong_ho dong_ho { get; set; }
    }
}
