//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dong_ho
    {
        public dong_ho()
        {
            this.sales_fact = new HashSet<sales_fact>();
        }
    
        public string masp { get; set; }
        public Nullable<int> id_loai { get; set; }
        public string thuong_hieu { get; set; }
        public decimal don_gia { get; set; }
        public Nullable<int> bao_hanh { get; set; }
        public string loai { get; set; }
        public string ten_sp { get; set; }
    
        public virtual loai loai1 { get; set; }
        public virtual ICollection<sales_fact> sales_fact { get; set; }
        public virtual dong_ho_sales dong_ho_sales { get; set; }
    }
}
