//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisView.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DW_WatchesEntities : DbContext
    {
        public DW_WatchesEntities()
            : base("name=DW_WatchesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<day> days { get; set; }
        public DbSet<dong_ho> dong_ho { get; set; }
        public DbSet<dong_ho_sales> dong_ho_sales { get; set; }
        public DbSet<khach_hang> khach_hang { get; set; }
        public DbSet<khach_hang_sales> khach_hang_sales { get; set; }
        public DbSet<loai> loais { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<time_by_day> time_by_day { get; set; }
        public DbSet<sales_fact> sales_fact { get; set; }
    }
}
