//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khach_hang
    {
        public khach_hang()
        {
            this.sales_fact = new HashSet<sales_fact>();
        }
    
        public int makh { get; set; }
        public string ten_kh { get; set; }
        public string dia_chi { get; set; }
        public string sdt { get; set; }
        public string email { get; set; }
    
        public virtual khach_hang_sales khach_hang_sales { get; set; }
        public virtual ICollection<sales_fact> sales_fact { get; set; }
    }
}
