//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loai
    {
        public loai()
        {
            this.dong_ho = new HashSet<dong_ho>();
        }
    
        public int id_loai { get; set; }
        public string ten_loai { get; set; }
    
        public virtual ICollection<dong_ho> dong_ho { get; set; }
    }
}
