//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalysisView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_fact
    {
        public Nullable<int> time_id { get; set; }
        public int so_luong { get; set; }
        public decimal so_tien { get; set; }
        public Nullable<int> makh { get; set; }
        public string masp { get; set; }
        public Nullable<System.DateTime> ngaygd { get; set; }
    
        public virtual dong_ho dong_ho { get; set; }
        public virtual khach_hang khach_hang { get; set; }
        public virtual time_by_day time_by_day { get; set; }
    }
}
